services:
  db:
    image: neo4j:2026
    container_name: neo4j-test-db
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - test-db-data:/data
      - test-db-logs:/logs
    environment:
      - NEO4J_AUTH=none
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s
    restart: unless-stopped

volumes:
  test-db-data:
  test-db-logs: